// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/maekawa/maekawa.proto

package maekawa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{0}
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{1}
}

func (x *LockRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LockRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Granted       bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{2}
}

func (x *LockResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LockResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReleaseRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type InquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InquireRequest) Reset() {
	*x = InquireRequest{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquireRequest) ProtoMessage() {}

func (x *InquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquireRequest.ProtoReflect.Descriptor instead.
func (*InquireRequest) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{4}
}

func (x *InquireRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *InquireRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type YieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YieldRequest) Reset() {
	*x = YieldRequest{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldRequest) ProtoMessage() {}

func (x *YieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldRequest.ProtoReflect.Descriptor instead.
func (*YieldRequest) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{5}
}

func (x *YieldRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *YieldRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_api_maekawa_maekawa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_maekawa_maekawa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_api_maekawa_maekawa_proto_rawDescGZIP(), []int{6}
}

func (x *GrantRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *GrantRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_maekawa_maekawa_proto protoreflect.FileDescriptor

const file_api_maekawa_maekawa_proto_rawDesc = "" +
	"\n" +
	"\x19api/maekawa/maekawa.proto\x12\amaekawa\"\a\n" +
	"\x05Empty\"D\n" +
	"\vLockRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"A\n" +
	"\fLockResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\"G\n" +
	"\x0eReleaseRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"K\n" +
	"\x0eInquireRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"I\n" +
	"\fYieldRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"I\n" +
	"\fGrantRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\x91\x02\n" +
	"\aMaekawa\x12:\n" +
	"\vRequestLock\x12\x14.maekawa.LockRequest\x1a\x15.maekawa.LockResponse\x126\n" +
	"\vReleaseLock\x12\x17.maekawa.ReleaseRequest\x1a\x0e.maekawa.Empty\x122\n" +
	"\aInquire\x12\x17.maekawa.InquireRequest\x1a\x0e.maekawa.Empty\x12.\n" +
	"\x05Yield\x12\x15.maekawa.YieldRequest\x1a\x0e.maekawa.Empty\x12.\n" +
	"\x05Grant\x12\x15.maekawa.GrantRequest\x1a\x0e.maekawa.EmptyB\x1fZ\x1draft-maekawa-sync/api/maekawab\x06proto3"

var (
	file_api_maekawa_maekawa_proto_rawDescOnce sync.Once
	file_api_maekawa_maekawa_proto_rawDescData []byte
)

func file_api_maekawa_maekawa_proto_rawDescGZIP() []byte {
	file_api_maekawa_maekawa_proto_rawDescOnce.Do(func() {
		file_api_maekawa_maekawa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_maekawa_maekawa_proto_rawDesc), len(file_api_maekawa_maekawa_proto_rawDesc)))
	})
	return file_api_maekawa_maekawa_proto_rawDescData
}

var file_api_maekawa_maekawa_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_maekawa_maekawa_proto_goTypes = []any{
	(*Empty)(nil),          // 0: maekawa.Empty
	(*LockRequest)(nil),    // 1: maekawa.LockRequest
	(*LockResponse)(nil),   // 2: maekawa.LockResponse
	(*ReleaseRequest)(nil), // 3: maekawa.ReleaseRequest
	(*InquireRequest)(nil), // 4: maekawa.InquireRequest
	(*YieldRequest)(nil),   // 5: maekawa.YieldRequest
	(*GrantRequest)(nil),   // 6: maekawa.GrantRequest
}
var file_api_maekawa_maekawa_proto_depIdxs = []int32{
	1, // 0: maekawa.Maekawa.RequestLock:input_type -> maekawa.LockRequest
	3, // 1: maekawa.Maekawa.ReleaseLock:input_type -> maekawa.ReleaseRequest
	4, // 2: maekawa.Maekawa.Inquire:input_type -> maekawa.InquireRequest
	5, // 3: maekawa.Maekawa.Yield:input_type -> maekawa.YieldRequest
	6, // 4: maekawa.Maekawa.Grant:input_type -> maekawa.GrantRequest
	2, // 5: maekawa.Maekawa.RequestLock:output_type -> maekawa.LockResponse
	0, // 6: maekawa.Maekawa.ReleaseLock:output_type -> maekawa.Empty
	0, // 7: maekawa.Maekawa.Inquire:output_type -> maekawa.Empty
	0, // 8: maekawa.Maekawa.Yield:output_type -> maekawa.Empty
	0, // 9: maekawa.Maekawa.Grant:output_type -> maekawa.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_maekawa_maekawa_proto_init() }
func file_api_maekawa_maekawa_proto_init() {
	if File_api_maekawa_maekawa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_maekawa_maekawa_proto_rawDesc), len(file_api_maekawa_maekawa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_maekawa_maekawa_proto_goTypes,
		DependencyIndexes: file_api_maekawa_maekawa_proto_depIdxs,
		MessageInfos:      file_api_maekawa_maekawa_proto_msgTypes,
	}.Build()
	File_api_maekawa_maekawa_proto = out.File
	file_api_maekawa_maekawa_proto_goTypes = nil
	file_api_maekawa_maekawa_proto_depIdxs = nil
}
