// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/maekawa/maekawa.proto

package maekawa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maekawa_RequestLock_FullMethodName = "/maekawa.Maekawa/RequestLock"
	Maekawa_ReleaseLock_FullMethodName = "/maekawa.Maekawa/ReleaseLock"
	Maekawa_Inquire_FullMethodName     = "/maekawa.Maekawa/Inquire"
	Maekawa_Failed_FullMethodName      = "/maekawa.Maekawa/Failed"
)

// MaekawaClient is the client API for Maekawa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaekawaClient interface {
	RequestLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*Empty, error)
	Inquire(ctx context.Context, in *InquireRequest, opts ...grpc.CallOption) (*YieldResponse, error)
	Failed(ctx context.Context, in *FailedRequest, opts ...grpc.CallOption) (*Empty, error)
}

type maekawaClient struct {
	cc grpc.ClientConnInterface
}

func NewMaekawaClient(cc grpc.ClientConnInterface) MaekawaClient {
	return &maekawaClient{cc}
}

func (c *maekawaClient) RequestLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, Maekawa_RequestLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maekawaClient) ReleaseLock(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Maekawa_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maekawaClient) Inquire(ctx context.Context, in *InquireRequest, opts ...grpc.CallOption) (*YieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YieldResponse)
	err := c.cc.Invoke(ctx, Maekawa_Inquire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maekawaClient) Failed(ctx context.Context, in *FailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Maekawa_Failed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaekawaServer is the server API for Maekawa service.
// All implementations must embed UnimplementedMaekawaServer
// for forward compatibility.
type MaekawaServer interface {
	RequestLock(context.Context, *LockRequest) (*LockResponse, error)
	ReleaseLock(context.Context, *ReleaseRequest) (*Empty, error)
	Inquire(context.Context, *InquireRequest) (*YieldResponse, error)
	Failed(context.Context, *FailedRequest) (*Empty, error)
	mustEmbedUnimplementedMaekawaServer()
}

// UnimplementedMaekawaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaekawaServer struct{}

func (UnimplementedMaekawaServer) RequestLock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLock not implemented")
}
func (UnimplementedMaekawaServer) ReleaseLock(context.Context, *ReleaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedMaekawaServer) Inquire(context.Context, *InquireRequest) (*YieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inquire not implemented")
}
func (UnimplementedMaekawaServer) Failed(context.Context, *FailedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Failed not implemented")
}
func (UnimplementedMaekawaServer) mustEmbedUnimplementedMaekawaServer() {}
func (UnimplementedMaekawaServer) testEmbeddedByValue()                 {}

// UnsafeMaekawaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaekawaServer will
// result in compilation errors.
type UnsafeMaekawaServer interface {
	mustEmbedUnimplementedMaekawaServer()
}

func RegisterMaekawaServer(s grpc.ServiceRegistrar, srv MaekawaServer) {
	// If the following call panics, it indicates UnimplementedMaekawaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maekawa_ServiceDesc, srv)
}

func _Maekawa_RequestLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaekawaServer).RequestLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maekawa_RequestLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaekawaServer).RequestLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maekawa_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaekawaServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maekawa_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaekawaServer).ReleaseLock(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maekawa_Inquire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InquireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaekawaServer).Inquire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maekawa_Inquire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaekawaServer).Inquire(ctx, req.(*InquireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maekawa_Failed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaekawaServer).Failed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maekawa_Failed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaekawaServer).Failed(ctx, req.(*FailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maekawa_ServiceDesc is the grpc.ServiceDesc for Maekawa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maekawa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maekawa.Maekawa",
	HandlerType: (*MaekawaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestLock",
			Handler:    _Maekawa_RequestLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _Maekawa_ReleaseLock_Handler,
		},
		{
			MethodName: "Inquire",
			Handler:    _Maekawa_Inquire_Handler,
		},
		{
			MethodName: "Failed",
			Handler:    _Maekawa_Failed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/maekawa/maekawa.proto",
}
