// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/maekawa.proto

package maekawapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Maekawa message type.
type MsgType int32

const (
	MsgType_REQUEST MsgType = 0 // worker requests CS entry from quorum members
	MsgType_REPLY   MsgType = 1 // quorum member grants a vote
	MsgType_RELEASE MsgType = 2 // worker releases CS, frees the vote
	MsgType_INQUIRE MsgType = 3 // voter asks current grant holder to yield (deadlock resolution)
	MsgType_YIELD   MsgType = 4 // grant holder yields back the vote to the voter
	MsgType_FAILED  MsgType = 5 // voter explicitly rejects a request (e.g. quorum member is going down)
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "REQUEST",
		1: "REPLY",
		2: "RELEASE",
		3: "INQUIRE",
		4: "YIELD",
		5: "FAILED",
	}
	MsgType_value = map[string]int32{
		"REQUEST": 0,
		"REPLY":   1,
		"RELEASE": 2,
		"INQUIRE": 3,
		"YIELD":   4,
		"FAILED":  5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_maekawa_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_maekawa_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_maekawa_proto_rawDescGZIP(), []int{0}
}

// single message type used for all Maekawa communication
type MaekawaMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=maekawa.MsgType" json:"type,omitempty"`
	SenderId      int32                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`             // node ID of the sender
	Clock         int64                  `protobuf:"varint,3,opt,name=clock,proto3" json:"clock,omitempty"`                                   // Lamport timestamp at send time
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                    // which task the CS request is for
	InquireClock  int64                  `protobuf:"varint,5,opt,name=inquire_clock,json=inquireClock,proto3" json:"inquire_clock,omitempty"` // only set in INQUIRE — clock of the grant being questioned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaekawaMsg) Reset() {
	*x = MaekawaMsg{}
	mi := &file_proto_maekawa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaekawaMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaekawaMsg) ProtoMessage() {}

func (x *MaekawaMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maekawa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaekawaMsg.ProtoReflect.Descriptor instead.
func (*MaekawaMsg) Descriptor() ([]byte, []int) {
	return file_proto_maekawa_proto_rawDescGZIP(), []int{0}
}

func (x *MaekawaMsg) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_REQUEST
}

func (x *MaekawaMsg) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MaekawaMsg) GetClock() int64 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *MaekawaMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MaekawaMsg) GetInquireClock() int64 {
	if x != nil {
		return x.InquireClock
	}
	return 0
}

// Ack is the response to every MaekawaMsg
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_maekawa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maekawa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_maekawa_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_maekawa_proto protoreflect.FileDescriptor

const file_proto_maekawa_proto_rawDesc = "" +
	"\n" +
	"\x13proto/maekawa.proto\x12\amaekawa\"\xa3\x01\n" +
	"\n" +
	"MaekawaMsg\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.maekawa.MsgTypeR\x04type\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x05R\bsenderId\x12\x14\n" +
	"\x05clock\x18\x03 \x01(\x03R\x05clock\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12#\n" +
	"\rinquire_clock\x18\x05 \x01(\x03R\finquireClock\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*R\n" +
	"\aMsgType\x12\v\n" +
	"\aREQUEST\x10\x00\x12\t\n" +
	"\x05REPLY\x10\x01\x12\v\n" +
	"\aRELEASE\x10\x02\x12\v\n" +
	"\aINQUIRE\x10\x03\x12\t\n" +
	"\x05YIELD\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x052;\n" +
	"\x0eMaekawaService\x12)\n" +
	"\x04Send\x12\x13.maekawa.MaekawaMsg\x1a\f.maekawa.AckB(Z&raft-maekawa/proto/maekawapb;maekawapbb\x06proto3"

var (
	file_proto_maekawa_proto_rawDescOnce sync.Once
	file_proto_maekawa_proto_rawDescData []byte
)

func file_proto_maekawa_proto_rawDescGZIP() []byte {
	file_proto_maekawa_proto_rawDescOnce.Do(func() {
		file_proto_maekawa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maekawa_proto_rawDesc), len(file_proto_maekawa_proto_rawDesc)))
	})
	return file_proto_maekawa_proto_rawDescData
}

var file_proto_maekawa_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_maekawa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_maekawa_proto_goTypes = []any{
	(MsgType)(0),       // 0: maekawa.MsgType
	(*MaekawaMsg)(nil), // 1: maekawa.MaekawaMsg
	(*Ack)(nil),        // 2: maekawa.Ack
}
var file_proto_maekawa_proto_depIdxs = []int32{
	0, // 0: maekawa.MaekawaMsg.type:type_name -> maekawa.MsgType
	1, // 1: maekawa.MaekawaService.Send:input_type -> maekawa.MaekawaMsg
	2, // 2: maekawa.MaekawaService.Send:output_type -> maekawa.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_maekawa_proto_init() }
func file_proto_maekawa_proto_init() {
	if File_proto_maekawa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maekawa_proto_rawDesc), len(file_proto_maekawa_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_maekawa_proto_goTypes,
		DependencyIndexes: file_proto_maekawa_proto_depIdxs,
		EnumInfos:         file_proto_maekawa_proto_enumTypes,
		MessageInfos:      file_proto_maekawa_proto_msgTypes,
	}.Build()
	File_proto_maekawa_proto = out.File
	file_proto_maekawa_proto_goTypes = nil
	file_proto_maekawa_proto_depIdxs = nil
}
