// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/maekawa.proto

package maekawapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaekawaService_Send_FullMethodName = "/maekawa.MaekawaService/Send"
)

// MaekawaServiceClient is the client API for MaekawaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// rpc -> all message types go through Send.
type MaekawaServiceClient interface {
	Send(ctx context.Context, in *MaekawaMsg, opts ...grpc.CallOption) (*Ack, error)
}

type maekawaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaekawaServiceClient(cc grpc.ClientConnInterface) MaekawaServiceClient {
	return &maekawaServiceClient{cc}
}

func (c *maekawaServiceClient) Send(ctx context.Context, in *MaekawaMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MaekawaService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaekawaServiceServer is the server API for MaekawaService service.
// All implementations must embed UnimplementedMaekawaServiceServer
// for forward compatibility.
//
// rpc -> all message types go through Send.
type MaekawaServiceServer interface {
	Send(context.Context, *MaekawaMsg) (*Ack, error)
	mustEmbedUnimplementedMaekawaServiceServer()
}

// UnimplementedMaekawaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaekawaServiceServer struct{}

func (UnimplementedMaekawaServiceServer) Send(context.Context, *MaekawaMsg) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMaekawaServiceServer) mustEmbedUnimplementedMaekawaServiceServer() {}
func (UnimplementedMaekawaServiceServer) testEmbeddedByValue()                        {}

// UnsafeMaekawaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaekawaServiceServer will
// result in compilation errors.
type UnsafeMaekawaServiceServer interface {
	mustEmbedUnimplementedMaekawaServiceServer()
}

func RegisterMaekawaServiceServer(s grpc.ServiceRegistrar, srv MaekawaServiceServer) {
	// If the following call panics, it indicates UnimplementedMaekawaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaekawaService_ServiceDesc, srv)
}

func _MaekawaService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaekawaMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaekawaServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaekawaService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaekawaServiceServer).Send(ctx, req.(*MaekawaMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// MaekawaService_ServiceDesc is the grpc.ServiceDesc for MaekawaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaekawaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maekawa.MaekawaService",
	HandlerType: (*MaekawaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MaekawaService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/maekawa.proto",
}
